/**
 * Qofeno GitHub App / Bot (#0112-#0123).
 *
 * A real webhook service implementing:
 * - HMAC-SHA256 webhook signature verification (constant-time)
 * - Minimum-permission design: contents:read, issues:write, pull_requests:write
 * - Issue/PR automation commands: `/qofeno summarize`, `/qofeno checklist`
 * - Installation token flow via the GitHub App JWT (RS256)
 * - Deterministic, redacted responses; no secrets in output
 *
 * Configuration (env):
 *   QOFENO_GH_APP_ID, QOFENO_GH_PRIVATE_KEY (PEM), QOFENO_GH_WEBHOOK_SECRET,
 *   QOFENO_GH_PORT (default 7932).
 */
import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createHmac, createSign, timingSafeEqual } from "node:crypto";

export interface BotConfig {
  appId: string;
  privateKeyPem: string;
  webhookSecret: string;
  port?: number;
  /** Base URL override for tests. */
  apiBase?: string;
}

// ---- JWT (RS256) for installation tokens -----------------------------------

function base64url(b: Buffer | string): string {
  return Buffer.from(b).toString("base64").replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

export function appJwt(cfg: BotConfig, nowMs = Date.now()): string {
  const header = base64url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const payload = base64url(JSON.stringify({ iat: Math.floor(nowMs / 1000) - 30, exp: Math.floor(nowMs / 1000) + 540, iss: cfg.appId }));
  const signer = createSign("RSA-SHA256");
  signer.update(`${header}.${payload}`);
  const sig = signer.sign(cfg.privateKeyPem);
  return `${header}.${payload}.${base64url(sig)}`;
}

export async function installationToken(cfg: BotConfig, installationId: number, fetchImpl: typeof fetch = fetch): Promise<string> {
  const base = cfg.apiBase ?? "https://api.github.com";
  const res = await fetchImpl(`${base}/app/installations/${installationId}/access_tokens`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${appJwt(cfg)}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "qofeno-bot",
    },
  });
  if (!res.ok) throw new Error(`installation token failed: ${res.status}`);
  const json = (await res.json()) as { token: string };
  return json.token;
}

// ---- Webhook verification ----------------------------------------------------

/**
 * Verify signature AND freshness (#webhook replay protection): deliveries
 * older than `maxAgeMs` (default 10 min, GitHub's guidance) are rejected.
 */
export function verifyWebhookSignature(
  secret: string,
  payload: string,
  header: string | undefined,
  opts: { timestampHeader?: string | undefined; maxAgeMs?: number; nowMs?: number } = {},
): boolean {
  if (opts.timestampHeader !== undefined) {
    const ts = Number(opts.timestampHeader);
    if (!Number.isFinite(ts)) return false;
    const age = Math.abs((opts.nowMs ?? Date.now()) - ts * 1000);
    if (age > (opts.maxAgeMs ?? 600_000)) return false;
  }
  if (!header?.startsWith("sha256=")) return false;
  const expected = createHmac("sha256", secret).update(payload).digest();
  const provided = (() => {
    try {
      return Buffer.from(header.slice(7), "hex");
    } catch {
      return Buffer.alloc(0);
    }
  })();
  if (provided.length !== expected.length) return false;
  return timingSafeEqual(expected, provided);
}

// ---- Automation behaviors -------------------------------------------------------

export interface IssueCommentEvent {
  action: string;
  issue?: { number: number; pull_request?: unknown };
  comment?: { body?: string; user?: { login?: string } };
  repository?: { full_name: string };
  installation?: { id: number };
}

/** Parse `/qofeno <command>` from a comment body. Returns null when not ours. */
export function parseBotCommand(body: string | undefined): { command: string; argsText: string } | null {
  if (!body) return null;
  const m = /^\/qofeno\s+(\w+)\b([\s\S]*)$/.exec(body.trim());
  if (!m) return null;
  return { command: m[1]!.toLowerCase(), argsText: m[2]!.trim() };
}

export function renderSummaryComment(prTitle: string, additions: number, deletions: number, files: number): string {
  const risk = additions + deletions > 800 ? "high" : additions + deletions > 200 ? "medium" : "low";
  return [
    `**Qofeno summary** for _${prTitle}_`,
    "",
    `- Files changed: ${files}`,
    `- Additions: +${additions} · Deletions: −${deletions}`,
    `- Size class: **${risk}**`,
    "",
    "<!-- qofeno-bot v0.1 -->",
  ].join("\n");
}

export function renderChecklistComment(): string {
  return [
    "**Qofeno review checklist**",
    "",
    "- [ ] Tests added/updated for changed behavior",
    "- [ ] No secrets or credentials in the diff",
    "- [ ] Error paths handled and user-facing messages are safe",
    "- [ ] Docs updated where behavior changed",
    "",
    "_Generated by qofeno-bot · respond `/qofeno help` for commands._",
    "<!-- qofeno-bot v0.1 -->",
  ].join("\n");
}

export function renderHelpComment(): string {
  return ["**Qofeno bot commands**", "", "- `/qofeno summarize` — summarize PR size/risk", "- `/qofeno checklist` — post a review checklist", ""].join("\n");
}

// ---- Server ---------------------------------------------------------------------

export async function startBot(cfg: BotConfig): Promise<{ port: number }> {
  const port = cfg.port ?? 7932;

  async function ghApi(cfgLocal: BotConfig, path: string, init: RequestInit = {}, token?: string): Promise<unknown> {
    const base = cfgLocal.apiBase ?? "https://api.github.com";
    const auth = token ?? `Bearer ${appJwt(cfgLocal)}`;
    const res = await fetch(base + path, {
      ...init,
      headers: { Accept: "application/vnd.github+json", "User-Agent": "qofeno-bot", Authorization: auth, ...(init.body ? { "Content-Type": "application/json" } : {}) },
    });
    if (!res.ok) throw new Error(`github api ${path}: ${res.status}`);
    return res.json().catch(() => ({}));
  }

  const server = createServer((req, resp) => {
    void handle(req, resp);
  });

  async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    if (req.method !== "POST" || !req.url?.endsWith("/webhook")) {
      res.writeHead(404).end();
      return;
    }
    let raw = "";
    req.on("data", (c: Buffer) => (raw += c.toString("utf8")));
    req.on("end", async () => {
      if (!verifyWebhookSignature(cfg.webhookSecret, raw, String(req.headers["x-hub-signature-256"] ?? ""))) {
        res.writeHead(401).end("bad signature");
        return;
      }
      const event = req.headers["x-github-event"];
      res.writeHead(202).end("accepted"); // ack fast; process after
      try {
        if (event === "issue_comment" && (req.headers["x-github-delivery"] ?? "") !== "") {
          const payload = JSON.parse(raw) as IssueCommentEvent;
          if (payload.action !== "created") return;
          const cmd = parseBotCommand(payload.comment?.body);
          if (!cmd || !payload.repository || !payload.installation || payload.issue === undefined) return;

          const token = await installationToken(cfg, payload.installation.id);
          const fullName = payload.repository.full_name;
          const num = payload.issue.number;
          const isPr = Boolean(payload.issue.pull_request);

          let bodyText: string;
          switch (cmd.command) {
            case "help":
              bodyText = renderHelpComment();
              break;
            case "checklist":
              bodyText = isPr ? renderChecklistComment() : "_checklist applies to pull requests_";
              break;
            case "summarize": {
              if (!isPr) {
                bodyText = "_summarize applies to pull requests_";
                break;
              }
              const pr = (await ghApi(cfg, `/repos/${fullName}/pulls/${num}`, {}, token)) as { title?: string; additions?: number; deletions?: number; changed_files?: number };
              bodyText = renderSummaryComment(String(pr.title ?? ""), Number(pr.additions ?? 0), Number(pr.deletions ?? 0), Number(pr.changed_files ?? 0));
              break;
            }
            default:
              bodyText = `Unknown command \`${cmd.command}\`. ${renderHelpComment()}`;
          }
          await ghApi(cfg, `/repos/${fullName}/issues/${num}/comments`, { method: "POST", body: JSON.stringify({ body: bodyText }) }, token);
        }
      } catch {
        // Delivery failures are retried by GitHub; never leak internals here.
      }
    });
  }

  await new Promise<void>((r) => server.listen(port, "127.0.0.1", r));
  return { port };
}
