/**
 * Machine-readable Command Compatibility Matrix.
 * Authoritative specification of all Qofeno commands, aliases, options,
 * TUI slash equivalents, permissions, and exit contracts.
 */

export interface CommandArgument {
  name: string;
  required: boolean;
  description: string;
}

export interface CommandOption {
  flag: string;
  alias?: string;
  type: "string" | "boolean" | "number";
  description: string;
  default?: string;
}

export interface CommandSpec {
  name: string;
  aliases: string[];
  description: string;
  syntax: string;
  arguments: CommandArgument[];
  options: CommandOption[];
  interactiveSupport: boolean;
  tuiSupport: boolean;
  noninteractiveSupport: boolean;
  slashEquivalent?: string;
  requiredPermissions: string[];
  exitCodes: number[];
  docPath: string;
  testPath: string;
}

export interface SlashCommandSpec {
  command: string;
  aliases: string[];
  description: string;
  arguments?: string;
  cliEquivalent?: string;
}

export const COMMAND_MATRIX: CommandSpec[] = [
  {
    name: "interactive",
    aliases: ["tui", "chat", "repl"],
    description: "Launch the interactive terminal TUI / REPL agent workspace",
    syntax: "qofeno [options]",
    arguments: [],
    options: [
      { flag: "model", alias: "m", type: "string", description: "Select model override (provider:model)" },
      { flag: "mode", type: "string", description: "Set mode (plan|review|execute|autonomous|restricted)" },
      { flag: "resume", type: "string", description: "Resume specific session ID" },
      { flag: "continue", alias: "c", type: "boolean", description: "Continue the most recent session" },
      { flag: "session-name", type: "string", description: "Set title for new session" },
      { flag: "project-root", type: "string", description: "Operating directory for project" },
      { flag: "local-only", type: "boolean", description: "Enforce local-only offline execution" },
      { flag: "profile", type: "string", description: "Configuration profile" },
    ],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: false,
    slashEquivalent: "/new",
    requiredPermissions: [],
    exitCodes: [0, 1, 2, 130],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "run",
    aliases: ["exec", "-p", "--print"],
    description: "Execute a one-shot prompt in non-interactive / headless mode",
    syntax: "qofeno run [prompt] [options] / qofeno -p <prompt>",
    arguments: [{ name: "prompt", required: false, description: "Prompt text or instruction to run" }],
    options: [
      { flag: "prompt", alias: "p", type: "string", description: "Headless prompt text" },
      { flag: "file", alias: "f", type: "string", description: "Read prompt from a file" },
      { flag: "output-format", type: "string", description: "Output format: text, json, jsonl", default: "text" },
      { flag: "model", alias: "m", type: "string", description: "Target model ID" },
      { flag: "mode", type: "string", description: "Execution mode (plan|review|execute|autonomous|restricted)" },
      { flag: "max-steps", type: "number", description: "Agent execution step limit", default: "12" },
      { flag: "timeout-ms", type: "number", description: "Maximum execution timeout in milliseconds", default: "300000" },
      { flag: "allowed-tools", type: "string", description: "Comma-separated list of permitted tools" },
      { flag: "auto-approve", alias: "y", type: "boolean", description: "Auto-approve safe operations" },
      { flag: "json", type: "boolean", description: "Shortcut for --output-format json" },
      { flag: "quiet", alias: "q", type: "boolean", description: "Suppress non-result outputs" },
      { flag: "local-only", type: "boolean", description: "Enforce strict offline local model execution" },
    ],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["model.infer"],
    exitCodes: [0, 1, 2, 3, 20, 21, 22, 124, 130],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "serve",
    aliases: ["server"],
    description: "Start local HTTP, WebSocket, and JSON-RPC server for Web/Desktop App & extensions",
    syntax: "qofeno serve [--port 7931] [--token <token>]",
    arguments: [],
    options: [
      { flag: "port", type: "number", description: "Port to listen on", default: "7931" },
      { flag: "token", type: "string", description: "Bearer authentication token for API security" },
      { flag: "host", type: "string", description: "Bind host address", default: "127.0.0.1" },
    ],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["server.listen"],
    exitCodes: [0, 1, 2, 130],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "model",
    aliases: ["models"],
    description: "List, inspect, install, select, and manage AI models and hardware recommendations",
    syntax: "qofeno model [list|recommend|info|use|install|search|status] [name]",
    arguments: [
      { name: "subcommand", required: false, description: "list, recommend, info, use, install, search, status" },
      { name: "model", required: false, description: "Model name or HuggingFace ID" },
    ],
    options: [
      { flag: "json", type: "boolean", description: "Format output as JSON" },
      { flag: "quant", type: "string", description: "Preferred quantization tier (e.g. Q4_K_M, Q8_0)" },
    ],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/model",
    requiredPermissions: [],
    exitCodes: [0, 1, 2, 4, 20],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "provider",
    aliases: ["providers"],
    description: "Configure and test local and cloud model providers",
    syntax: "qofeno provider [list|add|set|test|remove] [kind] [baseUrl]",
    arguments: [
      { name: "subcommand", required: false, description: "list, add, set, test, remove" },
      { name: "kind", required: false, description: "openai, openrouter, gemini, anthropic, ollama, custom" },
      { name: "baseUrl", required: false, description: "API base endpoint URL" },
    ],
    options: [
      { flag: "api-key", type: "string", description: "Provider API key (securely stored in vault)" },
      { flag: "json", type: "boolean", description: "Format output as JSON" },
    ],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/provider",
    requiredPermissions: ["credentials.manage"],
    exitCodes: [0, 1, 2, 4, 21],
    docPath: "docs/providers.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "session",
    aliases: ["sessions"],
    description: "Inspect, list, resume, rename, delete, and export conversation sessions",
    syntax: "qofeno session [list|resume|export|rm|rename|clear|info] [id]",
    arguments: [
      { name: "subcommand", required: false, description: "list, resume, export, rm, rename, clear, info" },
      { name: "id", required: false, description: "Session identifier" },
      { name: "extra", required: false, description: "Export path or new title" },
    ],
    options: [
      { flag: "json", type: "boolean", description: "Output in JSON format" },
      { flag: "limit", type: "number", description: "Maximum number of sessions to list" },
    ],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/sessions",
    requiredPermissions: ["storage.read", "storage.write"],
    exitCodes: [0, 1, 2, 4, 22],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "config",
    aliases: ["settings"],
    description: "View, update, reset, and inspect configuration and security policy",
    syntax: "qofeno config [get|set|list|reset|path|policy] [key] [value]",
    arguments: [
      { name: "subcommand", required: false, description: "get, set, list, reset, path, policy" },
      { name: "key", required: false, description: "Configuration key name" },
      { name: "value", required: false, description: "Value to assign" },
    ],
    options: [{ flag: "json", type: "boolean", description: "Output as JSON" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/config",
    requiredPermissions: [],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "doctor",
    aliases: ["diagnostics", "check"],
    description: "Run environment diagnostics, system capabilities, runtime health, and policy validation",
    syntax: "qofeno doctor [--json]",
    arguments: [],
    options: [{ flag: "json", type: "boolean", description: "Output diagnostic findings as structured JSON" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/doctor",
    requiredPermissions: [],
    exitCodes: [0, 1, 22],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "init",
    aliases: ["scaffold"],
    description: "Initialize Qofeno configuration, project prompt instructions, and ignore rules in current directory",
    syntax: "qofeno init [--force]",
    arguments: [],
    options: [{ flag: "force", type: "boolean", description: "Overwrite existing project configuration" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/init",
    requiredPermissions: ["fs.write"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "auth",
    aliases: ["login", "logout"],
    description: "Securely manage API credentials and platform authentication",
    syntax: "qofeno auth [login|logout|status] [provider]",
    arguments: [
      { name: "subcommand", required: false, description: "login, logout, status" },
      { name: "provider", required: false, description: "Target provider (openai, anthropic, gemini, openrouter)" },
    ],
    options: [{ flag: "token", type: "string", description: "Direct token input" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["credentials.manage"],
    exitCodes: [0, 1, 2, 21],
    docPath: "docs/security.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "share",
    aliases: [],
    description: "Export and securely package session summaries or transcripts",
    syntax: "qofeno share [session-id] [options]",
    arguments: [{ name: "session-id", required: false, description: "Session ID to export and share" }],
    options: [
      { flag: "format", type: "string", description: "Export format (json|markdown|html)", default: "markdown" },
      { flag: "out", type: "string", description: "Destination file path" },
    ],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/share",
    requiredPermissions: ["storage.read"],
    exitCodes: [0, 1, 2, 4],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "export",
    aliases: [],
    description: "Export conversation transcript to standard formats (JSON, Markdown, text)",
    syntax: "qofeno export [session-id] [dest] [--format md|json|html|text]",
    arguments: [
      { name: "session-id", required: false, description: "Session ID" },
      { name: "dest", required: false, description: "Target file path" },
    ],
    options: [{ flag: "format", type: "string", description: "Output format: json, md, html, text", default: "json" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/export",
    requiredPermissions: ["storage.read", "fs.write"],
    exitCodes: [0, 1, 2, 4],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "diff",
    aliases: [],
    description: "Render high-clarity color terminal diffs with width budget and syntax highlighting",
    syntax: "qofeno diff <file1> <file2>",
    arguments: [
      { name: "file1", required: true, description: "Original file path" },
      { name: "file2", required: true, description: "Modified file path" },
    ],
    options: [{ flag: "unified", type: "number", description: "Context line count", default: "3" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/diff",
    requiredPermissions: ["fs.read"],
    exitCodes: [0, 1, 2, 4],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "completion",
    aliases: ["completions"],
    description: "Generate shell completion scripts for Bash, Zsh, Fish, and PowerShell",
    syntax: "qofeno completion [bash|zsh|fish|powershell]",
    arguments: [{ name: "shell", required: false, description: "Target shell: bash, zsh, fish, powershell" }],
    options: [],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: [],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "update",
    aliases: ["upgrade"],
    description: "Check remote registry for available updates and self-update instructions",
    syntax: "qofeno update [--check]",
    arguments: [],
    options: [{ flag: "check", type: "boolean", description: "Only check if updates are available" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["net.request"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "setup",
    aliases: ["install-model"],
    description: "Guided local model discovery, hardware scoring, and installation wizard",
    syntax: "qofeno setup",
    arguments: [],
    options: [],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: false,
    slashEquivalent: "/setup",
    requiredPermissions: ["runtime.install"],
    exitCodes: [0, 1, 4, 20, 130],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "permissions",
    aliases: ["perms"],
    description: "Audit, grant, deny, and revoke deterministic security rules",
    syntax: "qofeno permissions [list|grant|deny|revoke|reset] [permission] [pattern]",
    arguments: [
      { name: "subcommand", required: false, description: "list, grant, deny, revoke, reset" },
      { name: "permission", required: false, description: "Permission key (e.g. fs.write, shell.exec)" },
      { name: "pattern", required: false, description: "Scope pattern" },
    ],
    options: [{ flag: "json", type: "boolean", description: "JSON format" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/permissions",
    requiredPermissions: ["security.manage"],
    exitCodes: [0, 1, 2],
    docPath: "docs/security.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "memory",
    aliases: ["mem"],
    description: "Manage project and global persistent user memory notes",
    syntax: "qofeno memory [list|add|forget|clear] [content|id]",
    arguments: [
      { name: "subcommand", required: false, description: "list, add, forget, clear" },
      { name: "arg", required: false, description: "Memory text or memory ID" },
    ],
    options: [{ flag: "json", type: "boolean", description: "Output in JSON format" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/memory",
    requiredPermissions: ["storage.read", "storage.write"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "knowledge",
    aliases: ["kb", "rag"],
    description: "Index project documents and perform semantic & keyword hybrid retrieval",
    syntax: "qofeno knowledge [index|search|list|clear] [file|query]",
    arguments: [
      { name: "subcommand", required: false, description: "index, search, list, clear" },
      { name: "arg", required: false, description: "File path or search query" },
    ],
    options: [{ flag: "limit", type: "number", description: "Search hit limit", default: "5" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/knowledge",
    requiredPermissions: ["fs.read", "storage.write"],
    exitCodes: [0, 1, 2, 22],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "repo",
    aliases: ["codebase"],
    description: "Codebase symbol intelligence, file indexing, and fast code search",
    syntax: "qofeno repo [index|search|symbols|status] [query|symbol]",
    arguments: [
      { name: "subcommand", required: false, description: "index, search, symbols, status" },
      { name: "arg", required: false, description: "Search query or symbol name" },
    ],
    options: [{ flag: "project-root", type: "string", description: "Project directory" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/repo",
    requiredPermissions: ["fs.read"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "tools",
    aliases: [],
    description: "List registered tools, schemas, and security risk classifications",
    syntax: "qofeno tools [list|info] [tool-name]",
    arguments: [
      { name: "subcommand", required: false, description: "list, info" },
      { name: "name", required: false, description: "Tool name" },
    ],
    options: [{ flag: "json", type: "boolean", description: "Output schema in JSON" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/tools",
    requiredPermissions: [],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "agents",
    aliases: ["agent"],
    description: "Run autonomous or constrained multi-step engineering agent workflows",
    syntax: "qofeno agents run \"<goal>\" --model <provider:model>",
    arguments: [
      { name: "subcommand", required: true, description: "run, list" },
      { name: "goal", required: false, description: "High-level goal description" },
    ],
    options: [
      { flag: "model", type: "string", description: "Model to execute with" },
      { flag: "max-steps", type: "number", description: "Max steps", default: "12" },
      { flag: "timeout-ms", type: "number", description: "Timeout in ms", default: "300000" },
      { flag: "allowed-tools", type: "string", description: "Tool whitelist" },
    ],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: "/plan",
    requiredPermissions: ["model.infer", "agent.execute"],
    exitCodes: [0, 1, 2, 20],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "workflows",
    aliases: ["workflow"],
    description: "Validate and run declarative engineering workflow pipelines",
    syntax: "qofeno workflows [validate|run|list] [file]",
    arguments: [
      { name: "subcommand", required: true, description: "validate, run, list" },
      { name: "file", required: false, description: "Workflow JSON file" },
    ],
    options: [],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["fs.read"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "extensions",
    aliases: ["ext", "plugins"],
    description: "Install, inspect, enable, disable, and isolate local extensions",
    syntax: "qofeno extensions [list|install|enable|disable|rm] [id|dir]",
    arguments: [
      { name: "subcommand", required: false, description: "list, install, enable, disable, rm" },
      { name: "target", required: false, description: "Extension ID or directory" },
    ],
    options: [],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["fs.read", "fs.write"],
    exitCodes: [0, 1, 2],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "backup",
    aliases: [],
    description: "Create SHA256 integrity-verified, encrypted backup archive of Qofeno state",
    syntax: "qofeno backup [dest-path]",
    arguments: [{ name: "dest", required: false, description: "Destination archive file path" }],
    options: [],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["fs.read", "fs.write"],
    exitCodes: [0, 1, 22],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "restore",
    aliases: [],
    description: "Restore Qofeno database and configuration from a verified backup archive",
    syntax: "qofeno restore <archive-path>",
    arguments: [{ name: "archive", required: true, description: "Path to backup archive" }],
    options: [],
    interactiveSupport: false,
    tuiSupport: false,
    noninteractiveSupport: true,
    slashEquivalent: undefined,
    requiredPermissions: ["fs.write"],
    exitCodes: [0, 1, 22],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "privacy",
    aliases: [],
    description: "Display local data mapping, storage paths, telemetry status, and network posture",
    syntax: "qofeno privacy",
    arguments: [],
    options: [{ flag: "json", type: "boolean", description: "Format output as JSON" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/privacy",
    requiredPermissions: [],
    exitCodes: [0, 1],
    docPath: "docs/privacy.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "version",
    aliases: ["-v", "--version"],
    description: "Print the current installed Qofeno version",
    syntax: "qofeno version / qofeno -v / qofeno --version",
    arguments: [],
    options: [{ flag: "json", type: "boolean", description: "JSON output" }],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/version",
    requiredPermissions: [],
    exitCodes: [0],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
  {
    name: "help",
    aliases: ["-h", "--help", "/?"],
    description: "Display comprehensive help, syntax, and command reference",
    syntax: "qofeno help [command]",
    arguments: [{ name: "command", required: false, description: "Command to inspect" }],
    options: [],
    interactiveSupport: true,
    tuiSupport: true,
    noninteractiveSupport: true,
    slashEquivalent: "/help",
    requiredPermissions: [],
    exitCodes: [0],
    docPath: "docs/cli-reference.md",
    testPath: "packages/cli/test/cli.test.ts",
  },
];

export const SLASH_COMMANDS: SlashCommandSpec[] = [
  { command: "/help", aliases: ["/?"], description: "Show available commands and usage guide", cliEquivalent: "qofeno help" },
  { command: "/local-model", aliases: ["/local"], description: "Discover, recommend and manage local models inside chat", cliEquivalent: "qofeno model recommend" },
  { command: "/quit", aliases: ["/exit", "/q"], description: "Exit the interactive session cleanly", cliEquivalent: undefined },
  { command: "/clear", aliases: ["/cls"], description: "Start a fresh session with clean context", cliEquivalent: "qofeno session clear" },
  { command: "/reset", aliases: ["/new"], description: "Reset session history and start fresh", cliEquivalent: "qofeno session clear" },
  { command: "/compact", aliases: ["/compress"], description: "Summarize and compact the session context window", cliEquivalent: undefined },
  { command: "/model", aliases: ["/m"], description: "List or select the active model", arguments: "[model_id]", cliEquivalent: "qofeno model" },
  { command: "/provider", aliases: [], description: "Configure or list available AI providers", arguments: "[provider_id]", cliEquivalent: "qofeno provider" },
  { command: "/mode", aliases: [], description: "Switch session mode (plan, review, execute, autonomous, restricted)", arguments: "<mode>", cliEquivalent: "qofeno --mode <mode>" },
  { command: "/sessions", aliases: ["/history"], description: "List recent conversation sessions", cliEquivalent: "qofeno session list" },
  { command: "/resume", aliases: [], description: "Resume a previous session by ID", arguments: "<session_id>", cliEquivalent: "qofeno session resume <id>" },
  { command: "/export", aliases: [], description: "Export the current session transcript (JSON, Markdown, HTML)", arguments: "[format] [path]", cliEquivalent: "qofeno export" },
  { command: "/share", aliases: [], description: "Generate a shareable summary transcript", cliEquivalent: "qofeno share" },
  { command: "/copy", aliases: [], description: "Copy last assistant response or code block", cliEquivalent: undefined },
  { command: "/cost", aliases: ["/usage"], description: "Show token usage, prompt tokens, and estimated cost for session", cliEquivalent: undefined },
  { command: "/config", aliases: ["/settings"], description: "View or set runtime configuration keys", arguments: "[key] [value]", cliEquivalent: "qofeno config" },
  { command: "/permissions", aliases: ["/perms"], description: "List active permission grants, denies, and security policy", cliEquivalent: "qofeno permissions list" },
  { command: "/memory", aliases: ["/mem"], description: "List or store persistent project memory notes", arguments: "[note text]", cliEquivalent: "qofeno memory" },
  { command: "/memory-forget", aliases: [], description: "Remove a memory note by ID", arguments: "<memory_id>", cliEquivalent: "qofeno memory forget <id>" },
  { command: "/knowledge", aliases: ["/kb"], description: "Index project files or search knowledge collections", arguments: "index <file> | search <query>", cliEquivalent: "qofeno knowledge" },
  { command: "/repo", aliases: [], description: "Codebase symbol intelligence and semantic search", arguments: "index | search <q> | symbols <name>", cliEquivalent: "qofeno repo" },
  { command: "/tools", aliases: [], description: "List all active tools and security risk levels", cliEquivalent: "qofeno tools" },
  { command: "/doctor", aliases: ["/diagnostics"], description: "Run system diagnostics and check provider health", cliEquivalent: "qofeno doctor" },
  { command: "/init", aliases: [], description: "Scaffold project configuration and instructions in current directory", cliEquivalent: "qofeno init" },
  { command: "/diff", aliases: [], description: "Inspect recent workspace modifications or diff two files", arguments: "[file1] [file2]", cliEquivalent: "qofeno diff" },
  { command: "/plan", aliases: [], description: "Draft a structured multi-step execution plan", arguments: "[goal]", cliEquivalent: "qofeno agents run" },
  { command: "/hardware", aliases: ["/hw"], description: "Inspect local hardware tier and model recommendation", cliEquivalent: "qofeno model recommend" },
  { command: "/setup", aliases: ["/install"], description: "Launch guided local model installer", arguments: "[model_name]", cliEquivalent: "qofeno setup" },
  { command: "/theme", aliases: [], description: "Set or preview color theme (dark, light, high-contrast, no-color)", arguments: "[theme_name]", cliEquivalent: "qofeno config set theme <name>" },
  { command: "/privacy", aliases: [], description: "View local storage paths and network posture", cliEquivalent: "qofeno privacy" },
  { command: "/version", aliases: [], description: "Show current Qofeno version", cliEquivalent: "qofeno version" },
];
